
- name: Setup database hosts
  hosts: all
  become: yes
 
  roles:
    - role: geerlingguy.postgresql
      tags: postgresql
    - role: geerlingguy.apache
      tags: apache
    - role: geerlingguy.php
      tags: php
